/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.clashcalculetor.GUI;

import com.mycompany.clashcalculetor.Dao.CartDao;
import com.mycompany.clashcalculetor.Models.Cart;
import com.mycompany.clashcalculetor.Service.ChestService;
import com.mycompany.clashcalculetor.Service.ClientService;
import com.mycompany.clashcalculetor.Service.DeckService;
import javax.swing.JOptionPane;

/**
 *
 * @author mello
 */
public class DeckAdd extends javax.swing.JFrame {

    DeckService deckService;
    public DeckAdd() {
        this.deckService = new DeckService();
        Cart[] carts=deckService.ListAllCarts();
        
        initComponents();
        for(Cart cart:carts){
            jComboBox1.addItem(cart.getName());
            jComboBox2.addItem(cart.getName());
            jComboBox3.addItem(cart.getName());
            jComboBox4.addItem(cart.getName());
            jComboBox5.addItem(cart.getName());
            jComboBox6.addItem(cart.getName());
            jComboBox7.addItem(cart.getName());
            jComboBox8.addItem(cart.getName());
            jComboBox9.addItem(cart.getName());
        }
    }

/**
     * Creates new form DeckAdd
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(11, 0));

        jPanel1.add(jComboBox1);

        jPanel1.add(jComboBox2);

        jPanel1.add(jComboBox4);

        jPanel1.add(jComboBox5);

        jPanel1.add(jComboBox6);

        jPanel1.add(jComboBox7);

        jPanel1.add(jComboBox8);

        jPanel1.add(jComboBox9);

        jRadioButton1.setText("I receve a chest");
        jPanel1.add(jRadioButton1);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cart carts[] = new Cart[8];
        carts[0]= new CartDao().findByName(String.valueOf(jComboBox1.getSelectedItem()));
        carts[1]= new CartDao().findByName(String.valueOf(jComboBox2.getSelectedItem()));
        carts[2]= new CartDao().findByName(String.valueOf(jComboBox9.getSelectedItem()));
        carts[3]= new CartDao().findByName(String.valueOf(jComboBox4.getSelectedItem()));
        carts[4]= new CartDao().findByName(String.valueOf(jComboBox5.getSelectedItem()));
        carts[5]= new CartDao().findByName(String.valueOf(jComboBox6.getSelectedItem()));
        carts[6]= new CartDao().findByName(String.valueOf(jComboBox7.getSelectedItem()));
        carts[7]= new CartDao().findByName(String.valueOf(jComboBox8.getSelectedItem()));
        if(deckService.addDeck(carts, ClientService.getCurrentClient())){
            JOptionPane.showMessageDialog(null, "It's impossible");
            setVisible(false);
            return;
        }
        //next chest
        if(jRadioButton1.isSelected()||JOptionPane.showConfirmDialog(this, "You receve a chest?")==0){
            new WhatChest().setVisible(true);
        }
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
